Default: &defaults
  user: yesod
  password: yesod
  host: localhost
  port: 5432
  database: yesod
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: yesod_test
  <<: *defaults

Staging:
  database: yesod_staging
  poolsize: 100
  <<: *defaults

Production:
  database: yesod_production
  poolsize: 100
  <<: *defaults
