Default: &defaults
  host: "*4" # any IPv4 host
  approot: "http://localhost:3000"
  port: 3000

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  approot: "http://yesod-oauth-demo.herokuapp.com"
  <<: *defaults
